# Generated by Django 3.2.18 on 2023-04-30 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('Guitar', 'Guitar'), ('Bass', 'Bass'), ('Keyboard', 'Keyboard'), ('Amplifier', 'Amplifier'), ('Drums', 'Drums'), ('DJ', 'DJ'), ('Studio', 'Studio'), ('Live Sound', 'Live Sound'), ('Orchestra', 'Orchestra'), ('Band', 'Band'), ('Lights', 'Lights'), ('Accessories', 'Accessories')], max_length=255)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(blank=True, choices=[('Non-Functioning', 'Non-Functioning'), ('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent'), ('Mint', 'Mint')], max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../gear-placeholder_l5xkcjb', upload_to='images/')),
                ('repair', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('sale', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('insured', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
