# Generated by Django 3.2.18 on 2023-05-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='image',
            field=models.ImageField(blank=True, default='../gear-placeholder_l5xkcj', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='value',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
