# Generated by Django 3.2.18 on 2023-04-30 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../rock-hand-gesture_eajhnb', upload_to='images/')),
                ('header_image', models.ImageField(blank=True, default='../default_header_jtvt3u', upload_to='images/')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('instruments', models.CharField(blank=True, choices=[('Electic Guitar', 'Electic Guitar'), ('Acoustic Guitar', 'Acoustic Guitar'), ('Bass Guitar', 'Bass Guitar'), ('Drums', 'Drums'), ('Percussion', 'Percussion'), ('Piano', 'Piano'), ('Keyboard', 'Keyboard'), ('Vocals', 'Vocals'), ('Saxophone', 'Saxophone'), ('Ukulele', 'Ukulele'), ('Violin', 'Violin'), ('Cello', 'Cello'), ('Trumpet', 'Trumpet'), ('Clarinet', 'Clarinet'), ('Accordion', 'Accordion'), ('Xylophone', 'Xylophone'), ('Trombone', 'Trombone'), ('Flute', 'Flute'), ('Oboe', 'Oboe'), ('Harp', 'Harp'), ('Harmonica', 'Harmonica'), ('Mandolin', 'Mandolin'), ('Bassoon', 'Bassoon'), ('Tuba', 'Tuba'), ('Viola', 'Viola'), ('Double Bass', 'Double Bass'), ('Synthesiser', 'Synthesiser'), ('Banjo', 'Banjo'), ('Bagpipes', 'Bagpipes'), ('Classical Guitar', 'Classical Guitar'), ('Cajon', 'Cajon'), ('Organ', 'Organ'), ('Didgeridoo', 'Didgeridoo'), ('Sitar', 'Sitar')], max_length=255)),
                ('genres', models.CharField(blank=True, choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Hip Hop', 'Hip Hop'), ('Jazz', 'Jazz'), ('Rhythm and Blues', 'Rhythm and Blues'), ('Electro', 'Electro'), ('Classical', 'Classical'), ('Blues', 'Blues'), ('Country', 'Country'), ('Heavy Metal', 'Heavy Metal'), ('Dance', 'Dance'), ('World', 'World'), ('Soul', 'Soul'), ('Punk', 'Punk'), ('Motown', 'Motown'), ('Funk', 'Funk'), ('Alt', 'Alt'), ('Folk', 'Folk'), ('Musical Theatre', 'Musical Theatre'), ('Reggae', 'Reggae'), ('Ska', 'Ska'), ('Latin', 'Latin'), ('Indie', 'Indie'), ('House', 'House'), ('Disco', 'Disco'), ('Easy Listening', 'Easy Listening'), ('Dubstep', 'Dubstep'), ('Experimental', 'Experimental'), ('Rock and Roll', 'Rock and Roll'), ('Swing', 'Swing'), ('Instrumental', 'Instrumental'), ('Ambient', 'Ambient'), ('Trance', 'Trance'), ('Bluegrass', 'Bluegrass'), ('Hardcore', 'Hardcore'), ('Grunge', 'Grunge'), ('Prog', 'Prog')], max_length=255)),
                ('expertise', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Novice', 'Novice'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert'), ('Pro', 'Pro')], max_length=255)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
