# Generated by Django 3.2.18 on 2023-05-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='genres',
            new_name='genre_1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='instruments',
            new_name='instrument_1',
        ),
        migrations.AddField(
            model_name='profile',
            name='genre_2',
            field=models.CharField(blank=True, choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Hip Hop', 'Hip Hop'), ('Jazz', 'Jazz'), ('Rhythm and Blues', 'Rhythm and Blues'), ('Electro', 'Electro'), ('Classical', 'Classical'), ('Blues', 'Blues'), ('Country', 'Country'), ('Heavy Metal', 'Heavy Metal'), ('Dance', 'Dance'), ('World', 'World'), ('Soul', 'Soul'), ('Punk', 'Punk'), ('Motown', 'Motown'), ('Funk', 'Funk'), ('Alt', 'Alt'), ('Folk', 'Folk'), ('Musical Theatre', 'Musical Theatre'), ('Reggae', 'Reggae'), ('Ska', 'Ska'), ('Latin', 'Latin'), ('Indie', 'Indie'), ('House', 'House'), ('Disco', 'Disco'), ('Easy Listening', 'Easy Listening'), ('Dubstep', 'Dubstep'), ('Experimental', 'Experimental'), ('Rock and Roll', 'Rock and Roll'), ('Swing', 'Swing'), ('Instrumental', 'Instrumental'), ('Ambient', 'Ambient'), ('Trance', 'Trance'), ('Bluegrass', 'Bluegrass'), ('Hardcore', 'Hardcore'), ('Grunge', 'Grunge'), ('Prog', 'Prog')], max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='genre_3',
            field=models.CharField(blank=True, choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Hip Hop', 'Hip Hop'), ('Jazz', 'Jazz'), ('Rhythm and Blues', 'Rhythm and Blues'), ('Electro', 'Electro'), ('Classical', 'Classical'), ('Blues', 'Blues'), ('Country', 'Country'), ('Heavy Metal', 'Heavy Metal'), ('Dance', 'Dance'), ('World', 'World'), ('Soul', 'Soul'), ('Punk', 'Punk'), ('Motown', 'Motown'), ('Funk', 'Funk'), ('Alt', 'Alt'), ('Folk', 'Folk'), ('Musical Theatre', 'Musical Theatre'), ('Reggae', 'Reggae'), ('Ska', 'Ska'), ('Latin', 'Latin'), ('Indie', 'Indie'), ('House', 'House'), ('Disco', 'Disco'), ('Easy Listening', 'Easy Listening'), ('Dubstep', 'Dubstep'), ('Experimental', 'Experimental'), ('Rock and Roll', 'Rock and Roll'), ('Swing', 'Swing'), ('Instrumental', 'Instrumental'), ('Ambient', 'Ambient'), ('Trance', 'Trance'), ('Bluegrass', 'Bluegrass'), ('Hardcore', 'Hardcore'), ('Grunge', 'Grunge'), ('Prog', 'Prog')], max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='instrument_2',
            field=models.CharField(blank=True, choices=[('Electic Guitar', 'Electic Guitar'), ('Acoustic Guitar', 'Acoustic Guitar'), ('Bass Guitar', 'Bass Guitar'), ('Drums', 'Drums'), ('Percussion', 'Percussion'), ('Piano', 'Piano'), ('Keyboard', 'Keyboard'), ('Vocals', 'Vocals'), ('Saxophone', 'Saxophone'), ('Ukulele', 'Ukulele'), ('Violin', 'Violin'), ('Cello', 'Cello'), ('Trumpet', 'Trumpet'), ('Clarinet', 'Clarinet'), ('Accordion', 'Accordion'), ('Xylophone', 'Xylophone'), ('Trombone', 'Trombone'), ('Flute', 'Flute'), ('Oboe', 'Oboe'), ('Harp', 'Harp'), ('Harmonica', 'Harmonica'), ('Mandolin', 'Mandolin'), ('Bassoon', 'Bassoon'), ('Tuba', 'Tuba'), ('Viola', 'Viola'), ('Double Bass', 'Double Bass'), ('Synthesiser', 'Synthesiser'), ('Banjo', 'Banjo'), ('Bagpipes', 'Bagpipes'), ('Classical Guitar', 'Classical Guitar'), ('Cajon', 'Cajon'), ('Organ', 'Organ'), ('Didgeridoo', 'Didgeridoo'), ('Sitar', 'Sitar')], max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='instrument_3',
            field=models.CharField(blank=True, choices=[('Electic Guitar', 'Electic Guitar'), ('Acoustic Guitar', 'Acoustic Guitar'), ('Bass Guitar', 'Bass Guitar'), ('Drums', 'Drums'), ('Percussion', 'Percussion'), ('Piano', 'Piano'), ('Keyboard', 'Keyboard'), ('Vocals', 'Vocals'), ('Saxophone', 'Saxophone'), ('Ukulele', 'Ukulele'), ('Violin', 'Violin'), ('Cello', 'Cello'), ('Trumpet', 'Trumpet'), ('Clarinet', 'Clarinet'), ('Accordion', 'Accordion'), ('Xylophone', 'Xylophone'), ('Trombone', 'Trombone'), ('Flute', 'Flute'), ('Oboe', 'Oboe'), ('Harp', 'Harp'), ('Harmonica', 'Harmonica'), ('Mandolin', 'Mandolin'), ('Bassoon', 'Bassoon'), ('Tuba', 'Tuba'), ('Viola', 'Viola'), ('Double Bass', 'Double Bass'), ('Synthesiser', 'Synthesiser'), ('Banjo', 'Banjo'), ('Bagpipes', 'Bagpipes'), ('Classical Guitar', 'Classical Guitar'), ('Cajon', 'Cajon'), ('Organ', 'Organ'), ('Didgeridoo', 'Didgeridoo'), ('Sitar', 'Sitar')], max_length=255),
        ),
    ]
