# Generated by Django 3.2.18 on 2023-04-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rig',
            name='attributes',
            field=models.CharField(blank=True, choices=[('Budget', 'Budget'), ('Versatile', 'Versatile'), ('High-End', 'High-End'), ('Tribute', 'Tribute'), ('Acoustic', 'Acoustic'), ('Electric', 'Electric'), ('Analogue', 'Analogue'), ('Digital', 'Digital'), ('Electro-Acoustic', 'Electro-Acoustic'), ('Pro', 'Pro'), ('Wireless', 'Wireless'), ('Portable', 'Portable')], max_length=255),
        ),
        migrations.AddField(
            model_name='rig',
            name='budget',
            field=models.CharField(blank=True, choices=[('£', '£'), ('££', '££'), ('£££', '£££'), ('££££', '££££'), ('£££££', '£££££')], max_length=255),
        ),
        migrations.AddField(
            model_name='rig',
            name='category',
            field=models.CharField(blank=True, choices=[('Guitar', 'Guitar'), ('Bass', 'Bass'), ('Keyboard', 'Keyboard'), ('Drums', 'Drums'), ('DJ', 'DJ'), ('Studio', 'Studio'), ('Live Sound', 'Live Sound'), ('Orchestra', 'Orchestra'), ('Band', 'Band')], max_length=255),
        ),
        migrations.AddField(
            model_name='rig',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rig',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rig',
            name='featured_image',
            field=models.ImageField(blank=True, default='../gear_addict_rig_placeholder_e0o12b', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='rig',
            name='gear_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rig',
            name='genre',
            field=models.CharField(blank=True, choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Hip Hop', 'Hip Hop'), ('Jazz', 'Jazz'), ('Rhythm and Blues', 'Rhythm and Blues'), ('Electro', 'Electro'), ('Classical', 'Classical'), ('Blues', 'Blues'), ('Country', 'Country'), ('Heavy Metal', 'Heavy Metal'), ('Dance', 'Dance'), ('World', 'World'), ('Soul', 'Soul'), ('Punk', 'Punk'), ('Motown', 'Motown'), ('Funk', 'Funk'), ('Alt', 'Alt'), ('Folk', 'Folk'), ('Musical Theatre', 'Musical Theatre'), ('Reggae', 'Reggae'), ('Ska', 'Ska'), ('Latin', 'Latin'), ('Indie', 'Indie'), ('House', 'House'), ('Disco', 'Disco'), ('Easy Listening', 'Easy Listening'), ('Dubstep', 'Dubstep'), ('Experimental', 'Experimental'), ('Rock and Roll', 'Rock and Roll'), ('Swing', 'Swing'), ('Instrumental', 'Instrumental'), ('Ambient', 'Ambient'), ('Trance', 'Trance'), ('Bluegrass', 'Bluegrass'), ('Hardcore', 'Hardcore'), ('Grunge', 'Grunge'), ('Prog', 'Prog')], max_length=255),
        ),
        migrations.AddField(
            model_name='rig',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='rig',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='rig',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
