# Generated by Django 3.2.18 on 2023-04-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0002_auto_20230430_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rig',
            old_name='attributes',
            new_name='attribute_1',
        ),
        migrations.RenameField(
            model_name='rig',
            old_name='genre',
            new_name='genre_1',
        ),
        migrations.AddField(
            model_name='rig',
            name='attribute_2',
            field=models.CharField(blank=True, choices=[('Budget', 'Budget'), ('Versatile', 'Versatile'), ('High-End', 'High-End'), ('Tribute', 'Tribute'), ('Acoustic', 'Acoustic'), ('Electric', 'Electric'), ('Analogue', 'Analogue'), ('Digital', 'Digital'), ('Electro-Acoustic', 'Electro-Acoustic'), ('Pro', 'Pro'), ('Wireless', 'Wireless'), ('Portable', 'Portable')], max_length=255),
        ),
        migrations.AddField(
            model_name='rig',
            name='genre_2',
            field=models.CharField(blank=True, choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Hip Hop', 'Hip Hop'), ('Jazz', 'Jazz'), ('Rhythm and Blues', 'Rhythm and Blues'), ('Electro', 'Electro'), ('Classical', 'Classical'), ('Blues', 'Blues'), ('Country', 'Country'), ('Heavy Metal', 'Heavy Metal'), ('Dance', 'Dance'), ('World', 'World'), ('Soul', 'Soul'), ('Punk', 'Punk'), ('Motown', 'Motown'), ('Funk', 'Funk'), ('Alt', 'Alt'), ('Folk', 'Folk'), ('Musical Theatre', 'Musical Theatre'), ('Reggae', 'Reggae'), ('Ska', 'Ska'), ('Latin', 'Latin'), ('Indie', 'Indie'), ('House', 'House'), ('Disco', 'Disco'), ('Easy Listening', 'Easy Listening'), ('Dubstep', 'Dubstep'), ('Experimental', 'Experimental'), ('Rock and Roll', 'Rock and Roll'), ('Swing', 'Swing'), ('Instrumental', 'Instrumental'), ('Ambient', 'Ambient'), ('Trance', 'Trance'), ('Bluegrass', 'Bluegrass'), ('Hardcore', 'Hardcore'), ('Grunge', 'Grunge'), ('Prog', 'Prog')], max_length=255),
        ),
    ]
