# Generated by Django 3.2.18 on 2023-04-30 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0003_auto_20230430_1519'),
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='rig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='rigs.rig'),
        ),
    ]
